### ISSUE TITLE
linkedin bot

### ISSUE THREAD

**Issue by DatCGI2net** [dinesh829269/hrm#1]
Hello dev1,

I am warning you about the linkedin project. That will be financial risk for you. Your payment is not guaranteed and your contract can be terminated immediately. They did that to me and not pay for my full month service.

Take care!

Dat

**Comment by dinesh829269** [comment]
Hi Dat, 
Thank you

**Comment by osamajameelahmad** [comment]
@DatCGI2net can I have your skype or email I have started to work on this. I want to ask some thing.

**Comment by osamajameelahmad** [comment]
@dinesh829269 did you also worked with them?

**Comment by DatCGI2net** [comment]
No, they fired me last month without paying a dime. And many other developers were the same. Just check my contact page on my website.

**Comment by developerexp08** [comment]
I have emailed you via your contact page.

**Comment by osamajameelahmad** [comment]
I have emailed you from your website contact page. Do you have anything else as proof so we can complaint them?

**Comment by DatCGI2net** [comment]
Yes, I replied already

**Comment by dinesh829269** [comment]
@osamajameelahmad yes i worked with them for 4-5 days, but everything seems fake there so i backed from the job
